# Generated by Django 3.1.2 on 2020-10-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('roles', models.JSONField(default=dict)),
                ('description', models.TextField(null=True)),
                ('keywords', models.ManyToManyField(blank=True, to='contents.Keyword')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contents.location')),
            ],
            options={
                'db_table': 'leaderships',
            },
        ),
    ]
